### PR TITLE
Use rollup babel

### PR DESCRIPTION
**Pull request by Fridus**
Use babel in tests and build with the same configuration.

### CODE REVIEW

**Comment by Fridus** [comment]
@developit Hi !
Could you check this PR asap ? This PR fix usage of `withText` https://github.com/synacor/preact-i18n/issues/5
I need this fix quickly for one of my projects :)

**Comment by billneff79** [comment]
Looking at it now.  I can merge the PR, but I think only @developit has the rights to push a new package to npm, and he's on vacation right now.  I'll see if I can flag him down.

**Comment by billneff79** [comment]
gzipped bundle size grew by 38% with this change. investigating

**Comment by billneff79** [comment]
seems like the size diff is mostly related to the es2015 plugin for babel creating polyfills for some things that buble does not, such as `typeof` and it is a little bigger for creating a `class`

**Comment by billneff79** [comment]
if we are going to use babel instead of buble (which I'm fine with), then we can also get rid of the assign ponyfill in `/lib/utils`

**Comment by billneff79** [comment]
Closing this one and will merge my minor adjustments in PR #7

**Pull request closed without merging**
