### PR TITLE
Merge master into preactX

### PR DESCRIPTION
**Pull request by pl12133**

### CODE REVIEW

**Comment by silentsakky** [comment]
@billneff79 can we get this merged? wanted support of https://github.com/synacor/preact-i18n/commit/fe3f4f5f853a49d1011b5f6aad39c7084ea8b2a6 for preactx as well

**Comment by billneff79** [comment]
@pl12133 - Is this still safe to merge?

**Comment by billneff79** [comment]
I'll merge but leave it up to @pl12133 to do a release when he's ready.  Looking through the file changes, it all looks good to me.

**Comment by pl12133** [comment]
Thanks @billneff79, this was working in all my tests before so I'll re-test today and do a release.

**Comment by pl12133** [comment]
Released in `preact-i18n@2.2.0-preactx`

**Pull request merged**
