### PR TITLE
Add initial typings

### PR DESCRIPTION
**Pull request by sammkj**
Related: #12

### CODE REVIEW

**Comment by billneff79** [comment]
Thanks for the PR @sammkj .  

It looks like it is missing the function definitions for `intl` and `withText`.  Did you leave those out on purpose.

Also, I'm not super familiar with typescript, but preact defines a typings.json file and it also packages the .d.ts file as part of the build steps in package.json, which this PR doesn't do.  My guess is that this PR isn't quite complete enough to have this work for the general public yet.

**Comment by billneff79** [comment]
Build steps from preact: https://github.com/developit/preact/blob/master/package.json#L13-L14

**Comment by sammkj** [comment]
@billneff79 , I'm not using any of those two APIs at the moment. But I can write definitions for it. Let me make some changes.

**Comment by billneff79** [comment]
@jtrollia - I'll close this and reference the definitely typed typings

**Pull request closed without merging**
